### PR TITLE
bug during concurrent access in crypto translator

### PR DESCRIPTION
**Pull request by kinsu**
in glusterfs during XTS encryption ivec might get corrupted
from parallel operations.

I have reproduced this issue in a plain glusterfs cluster with just one brick. The important part is the file size because we have parallel reads. Maybe the bigger the file, the bigger the possibility for collisions?
Its related to crypro xlator, read part. by disabling caching in gluster fuse client you get different content every time you drop the caches in kernel side while keeping the brick file intact (randomly). 
At all times the problem appears few blocks while the others are fine.

good
[2019-08-26 09:25:03.376342] D [data.c:148:crypto_print_raw_pol] 0-vangelis: info: [keys] len : 256 block_bits: 12 offset: 27860992  data : 0050AA0100000000000000000000000004DE572638DEE7F7FBA83986D92DD922F2C12B29C191F7FA0CEB25D8E871F78D72A800B43350DCD3CD7AD222E49AD255777CC20C41F8DC67FE2A0EF129E000776...
[2019-08-26 09:25:03.376639] D [data.c:148:crypto_print_raw_pol] 0-vangelis: info: [data] len : 4096 block_bits: 0 offset: 27860992  data : 333632313531330A333632313531340A333632313531350A333632313531360A333632313531370A333632313531380A333632313531390A333632313532300A333632313532310A...

bad
[2019-08-26 09:42:31.146943] D [data.c:148:crypto_print_raw_pol] 0-vangelis: info: [keys] len : 256 block_bits: 12 offset: 27860992  data : 0010AB0100000000000000000000000004DE572638DEE7F7FBA83986D92DD922F2C12B29C191F7FA0CEB25D8E871F78D72A800B43350DCD3CD7AD222E49AD255777CC20C41F8DC67FE2A0EF129E000776CED247F3684...
[2019-08-26 09:42:31.147251] D [data.c:148:crypto_print_raw_pol] 0-vangelis: info: [data] len : 4096 block_bits: 0 offset: 27860992  data : AD4B4A3F0076507795ED65523C65F64C3807EE6A73E8808B250C58DF43D6E109ECEAE29B1A16C0A0189EFA93AD453DAE8E59F301C8C57...

As can be seen from the below log there reason is that iv changes within different readv operations handled in parallel:
[2019-08-26 16:04:54.099875] D [data.c:25:crypto_print_raw_pol] 0-vangelis: info: set_iv_aes_xts len : 16 block_bits: 0 offset: 180224  data : 00C00200000000000000000000000000
[2019-08-26 16:04:54.100102] D [data.c:25:crypto_print_raw_pol] 0-vangelis: info: [keys] len : 256 block_bits: 12 offset: 180224  data : 0060040000000000000000000000000039A0D5D51D9CE8386AD1E5F00C46FC0F4D43BE66A28530DFB6A929C9D78486C2AA2BC831EFC68EB9142C1916612DAF0BF532DE5045ED4688F...
[2019-08-26 16:04:54.100966] D [data.c:25:crypto_print_raw_pol] 0-vangelis: info: [data] len : 4096 block_bits: 0 offset: 180224  data : 049A1DAACF2B0602294603C5EBB6372CB721E965994E34B3196EE6593C1144306E3774E76FB78FA506C3766A52355BAAB7AC0366B45049F2...

### CODE REVIEW

**Review by amarts — APPROVED** [review]
LGTM

**Comment by amarts** [comment]
Just curios, how are you using the feature ? and with which version?

**Comment by kinsu** [comment]
We are using it with 5.6. We are using it for one of the volumes dedicated for files we want to protect . It suits us because it provides a handy way to treat in-transit and at-rest encryption. It would be great if crypto would be re-added to the official translators but as i understood not many are using it ?

**Comment by amarts** [comment]
Good to know about the usecase.

> It would be great if crypto would be re-added to the official translators but as i understood not many are using it ?

We are moving towards a setup where people can have their own translators maintained by themselves, and host in a separate repo. So, unless it is very common usecase, we may not add crypto back in main repo.

**Comment by kinsu** [comment]
thanks for the information! just wondering, other users of gluster dont have the encryption use case at all or they achieve the encryption via encrypted partitions along with ssl communication between brick process and client ?

**Pull request merged**
